eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true

    service-url:
      defaultZone: http://localhost:8889/eureka/
    instance:
    leaseRenewalIntervalInSeconds: 15 # Set the lease renewal interval to 15 seconds
